name: Nuget Release

on:
  release:
    types: [created, edited]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Build/Check for compile errors (dotnet build)
        working-directory: "MaLoIdentBo4eMapper"
        run: dotnet build --configuration Release
      - name: Run Unit Tests (dotnet test) # never ever release with failing tests!
        working-directory: "MaLoIdentBo4eMapper"
        run: dotnet test --configuration Release
  push_release:
    needs: run_tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - uses: olegtarasov/get-tag@v2.1
        id: tagTBC
        with:
          tagRegex: "v(\\d+\\.\\d+\\.\\d+)"
      - name: copy README.md to package folder
        run: cp README.md MaLoIdentBo4eMapper/MaLoIdentBo4eMapper/README.md
      - name: Build/Check for compile errors (dotnet build)
        working-directory: "MaLoIdentBo4eMapper"
        run: dotnet build --configuration Release
      - name: Create Package MaLoIdentBo4eMapper (dotnet pack)
        working-directory: "MaLoIdentBo4eMapper/MaLoIdentBo4eMapper"
        run: dotnet pack MaLoIdentBo4eMapper.csproj --configuration Release -p:PackageVersion="${{ steps.tagTBC.outputs.tag }}"
      - name: Nuget push MaLoIdentBo4eMapper
        working-directory: "MaLoIdentBo4eMapper/MaLoIdentBo4eMapper"
        # token: https://github.com/Hochfrequenz/MaLoIdentBo4eMapper/settings/secrets/actions/NUGET_ORG_PUSH_TOKEN
        # expires 2025-09-27; token is owned by konstantin as of now.
        run: |
          dotnet nuget push ./bin/Release/*.nupkg --api-key ${{ secrets.NUGET_ORG_PUSH_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
